import com.google.gson.annotations.SerializedName


data class Businesses (
	@SerializedName("id") val id : String,
	@SerializedName("businessID") val businessID : String,
	@SerializedName("businessName") val businessName : String,
	@SerializedName("receiptAmount") val receiptAmount : String,
	@SerializedName("statusID") val statusID : String,
	@SerializedName("status") val status : String,
	@SerializedName("businessType") val businessType : String,
	@SerializedName("subCountyID") val subCountyID : String,
	@SerializedName("subCountyName") val subCountyName : String,
	@SerializedName("wardID") val wardID : String,
	@SerializedName("wardName") val wardName : String,
	@SerializedName("plotNumber") val plotNumber : String,
	@SerializedName("physicalAddress") val physicalAddress : String,
	@SerializedName("buildingName") val buildingName : String,
	@SerializedName("buildingOccupancy") val buildingOccupancy : String,
	@SerializedName("floorNo") val floorNo : String,
	@SerializedName("roomNo") val roomNo : String,
	@SerializedName("premiseSize") val premiseSize : String,
	@SerializedName("numberOfEmployees") val numberOfEmployees : String,
	@SerializedName("tonnage") val tonnage : String,
	@SerializedName("businessDes") val businessDes : String,
	@SerializedName("businessCategory") val businessCategory : String,
	@SerializedName("businessSubCategory") val businessSubCategory : String,
	@SerializedName("incomeTypeID") val incomeTypeID : String,
	@SerializedName("feeID") val feeID : String,
	@SerializedName("businessEmail") val businessEmail : String,
	@SerializedName("postalAddress") val postalAddress : String,
	@SerializedName("postalCode") val postalCode : String,
	@SerializedName("businessPhone") val businessPhone : String,
	@SerializedName("contactPersonNames") val contactPersonNames : String,
	@SerializedName("contactPersonIDNo") val contactPersonIDNo : String,
	@SerializedName("businessRole") val businessRole : String,
	@SerializedName("contactPersonPhone") val contactPersonPhone : String,
	@SerializedName("contactPersonEmail") val contactPersonEmail : String,
	@SerializedName("fullNames") val fullNames : String,
	@SerializedName("ownerID") val ownerID : String,
	@SerializedName("ownerPhone") val ownerPhone : String,
	@SerializedName("ownerEmail") val ownerEmail : String,
	@SerializedName("kraPin") val kraPin : String,
	@SerializedName("createdBy") val createdBy : String,
	@SerializedName("createdByIDNo") val createdByIDNo : String,
	@SerializedName("dateCreated") val dateCreated : String,
	@SerializedName("lat") val lat : String,
	@SerializedName("lng") val lng : String,
	@SerializedName("liquor") val liquor : String,
	@SerializedName("conservancy") val conservancy : String,
	@SerializedName("fireLicence") val fireLicence : String,
	@SerializedName("liquorLicence") val liquorLicence : String,
)