import com.google.gson.annotations.SerializedName

data class Data (

	@SerializedName("userdata") val userdata : Userdata,
	@SerializedName("parking") val parking : Parking,
	@SerializedName("clampreasons") val clampreasons : List<Clampreasons>,
	@SerializedName("receiptDetails") val receiptDetails : ReceiptDetails,
	@SerializedName("receiptInfos") val receiptInfos : List<ReceiptInfos>,
	@SerializedName("permit") val permit : Permit,
	@SerializedName("queries") val queries : List<Queries>,
	@SerializedName("Transactions") val transactions : List<Transactions>,
	@SerializedName("shortcodes") val shortcodes : List<Shortcodes>,
	@SerializedName("Push") val push : Push,
	@SerializedName("incomeTypes") val incomeTypes : List<IncomeTypes>,
	@SerializedName("feesAndCharges") val feesAndCharges : List<FeesAndCharges>,
	@SerializedName("feesAndCharge") val feesAndCharge : FeesAndCharges,
	@SerializedName("billGenerated") val billGenerated : BillGenerated,
	@SerializedName("zones") val zones : List<Zones>,
	@SerializedName("categories") val categories : List<Categories>,
	@SerializedName("durations") val durations : List<Durations>,
	@SerializedName("billDetails") val billDetails : BillDetails,
	@SerializedName("billInfo") val billInfo : List<BillInfo>,
	@SerializedName("addresses") val addresses : List<Addresses>,
	@SerializedName("wards") val wards : List<Wards>,
	@SerializedName("subCounties") val subCounties : List<SubCounties>,
	@SerializedName("tradeCategories") val tradeCategories : List<TradeCategories>,
	@SerializedName("tradeSubCategories") val tradeSubCategories : List<TradeSubCategories>,
	@SerializedName("user") val user : User,
	@SerializedName("transaction") val transaction : Transaction,
	@SerializedName("overview") val overview : List<Overview>,
	@SerializedName("MyOverview") val myOverview : MyOverview,
	@SerializedName("myHistory") val myHistory : List<MyHistory>,
	@SerializedName("users") val users : List<Users>,
	@SerializedName("subCountiesRevenue") val subCountiesRevenue : List<SubCountiesRevenue>,
	@SerializedName("totalAmount") val totalAmount : TotalAmount,
	@SerializedName("totalItems") val totalItems : Int,
	@SerializedName("collectionsBreakdown") val collectionsBreakdown : List<CollectionsBreakdown>,
	@SerializedName("streams") val streams : List<Streams>,
	@SerializedName("floors") val floors : List<Floors>,
	@SerializedName("roles") val roles : List<Roles>,
	@SerializedName("tonnage") val tonnage : List<Tonnage>,
	@SerializedName("businesses") val businesses : List<Businesses>,
	@SerializedName("entries") val entries : Entries,
	@SerializedName("business") val business : Business,
	@SerializedName("statuses") val statuses : List<Statuses>,
	@SerializedName("bill") val bill : Bill,
	@SerializedName("receipt") val receipt : Receipt,
	@SerializedName("businessTypes") val businessTypes : List<BusinessTypes>

)